name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache CMake dependencies
        uses: actions/cache@v2
        with:
          path: |
            build/
            ~/.cmake
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      # Setup language tools
      - name: Setup zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      # Dependencies and build
      - name: Install Criterion
        run: |
          sudo apt-get update
          sudo apt-get install -y libcriterion-dev ninja-build

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Go dependencies
        run: go mod download

      # Run tests
      - name: Build and test CMake/CTest
        run: |
          mkdir -p build
          cd build
          cmake .. -G Ninja
          ninja
          ctest --output-on-failure

      - name: Run Go tests
        run: CGO_ENABLED=0 go test ./...

      - name: Run pytest
        run: pytest -xv

      - name: Run zig tests
        run: zig build test
